version: "3"
services:
    app:
        container_name: "chatdb"
        build:
            context: .
            dockerfile: Dockerfile
        image: chatdb
        volumes:
            - ./:/home/chatdb
        tty: true
        networks:
            - app-tier
    db:
        container_name: "neo4j"
        image: neo4j:4.1
        environment:
            NEO4J_AUTH: neo4j/your_password
        tty: true
        ports:
            - "7474:7474"
            - "7687:7687"
        networks:
            - app-tier
networks:
  app-tier:
    driver: bridge
